version: '4'

services:
  admin_api:
    build:
      context: ./admin_api
      dockerfile: ./docker/dockerfile
    container_name: admin_api
    hostname: ${ADMIN_API_HOST}
    restart: unless-stopped
    environment:
      APP_MODE: ${ADMIN_APP_MODE}
      REFRESH_MIGRATIONS: ${REFRESH_MIGRATIONS}

      ADMIN_NAME: ${ADMIN_API_USER_NAME}
      ADMIN_EMAIL: ${ADMIN_API_USER_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_API_USER_PASSWORD}

      DB_HOST: ${ADMIN_DB_HOST}
      DB_PORT: ${ADMIN_DB_PORT}
      DB_DATABASE: ${ADMIN_DB_DATABASE}
      DB_USERNAME: ${ADMIN_DB_USERNAME}
      DB_PASSWORD: ${ADMIN_API_USER_PASSWORD}

      DB_HOST_TEST: ${ADMIN_DB_HOST_TEST}
      DB_PORT_TEST: ${ADMIN_DB_PORT_TEST}
      DB_DATABASE_TEST: ${ADMIN_DB_DATABASE_TEST}
      DB_USERNAME_TEST: ${ADMIN_DB_USERNAME_TEST}
      DB_PASSWORD_TEST: ${ADMIN_DB_PASSWORD_TEST}
    ports:
      - 8400:${ADMIN_API_PORT}
    volumes:
      - ./admin_api:/app
    depends_on:
      admin_db:
        condition: service_healthy
      admin_db_test:
        condition: service_healthy
    networks:
      - app
  
  admin_db:
    image: mysql:8.0.28
    restart: unless-stopped
    container_name: admin_db
    hostname: ${ADMIN_DB_HOST}
    environment:
      MYSQL_DATABASE: ${ADMIN_DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${ADMIN_DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - 33066:${ADMIN_DB_PORT}
    volumes:
      - ./admin_db/db:/var/lib/mysql
    networks:
      - app

  admin_db_test:
      image: mysql:8.0.28
      restart: unless-stopped
      container_name: admin_db_test
      hostname: ${ADMIN_DB_HOST_TEST}
      environment:
        MYSQL_DATABASE: ${ADMIN_DB_DATABASE_TEST}
        MYSQL_ROOT_PASSWORD: ${ADMIN_DB_PASSWORD_TEST}
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10
      ports:
        - 33077:${ADMIN_DB_PORT_TEST}
      volumes:
        - ./admin_db/db_test:/var/lib/mysql
      networks:
        - app

  adminer:
      image: adminer
      container_name: adminer
      ports:
        - "8401:8080"
      depends_on:
        - admin_db
        - admin_db_test
      networks:
        - app
networks:
  app:
